version: '3.5'
services:

  app:
    build: .
    image: &app app
    restart: "no"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file: &envfile
      - .env.production
    ports:
      - "8000:8000"
    # volumes:
    #   - ./app:/app
    depends_on:
      - broker
    restart: always

  worker:
    build: .
    image: *app
    restart: "no"
    env_file: *envfile
    command: ["celery", "--app=worker.worker.app", "worker", "--concurrency=1", "--hostname=worker@%h", "--loglevel=INFO"]
    # volumes:
    #   - ./app:/app
    depends_on:
      - broker
    restart: always
    
  flower:
    image: zoomeranalytics/flower:0.9.1-4.0.2
    restart: "no"
    env_file: *envfile
    ports:
      - "5555:5555"
    depends_on:
      - broker
    restart: always

  broker:
    image: rabbitmq:3.8.9-management
    env_file: *envfile
    ports:
      - 5672:5672
      - 15672:15672
    restart: always